global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']  # This lets you monitor Prometheus itself

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld-exporter:9104']
