image: docker:latest

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

before_script:
  - docker info

build_app:
  stage: build
  script:
    - docker build -t java-web-app .
